--TO SELECT ANY RANDOM QUESTIONS FROM ANY ONE SUBJECT
SELECT QID FROM QUESTIONS WHERE SID = 1
ORDER BY RAND () LIMIT 5;

--SELECT NAME,SCORE.USN,TIME_TAKEN,SCORE FROM SCORE,USERS WHERE SID = 1 and SCORE.USN = USERS.USN ORDER BY SCORE DESC,TIME_TAKEN;

WITH RankedScores AS (
    SELECT
        NAME,
        SCORE.USN,
        TIME_TAKEN,
        SCORE,
        ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY SCORE DESC, TIME_TAKEN ASC) AS RowNum
    FROM SCORE
    JOIN USERS ON SCORE.USN = USERS.USN
    WHERE SID = 1
)
SELECT NAME, USN, TIME_TAKEN, SCORE
FROM RankedScores
WHERE RowNum = 1
ORDER BY SCORE DESC, TIME_TAKEN ASC;

SELECT SNAME,TIME_TAKEN,SCORE FROM USERS,SCORE,SUBJECT WHERE SCORE.SID = SUBJECT.SID AND SCORE.USN = USERS.USN AND USERS.USN = '1122334455';

SELECT SUM(SCORE) FROM SCORE WHERE USN='1122334455' AND SID=1;


delete FROM `questions` WHERE qid=46;
delete from options where qid=46;
ALTER TABLE questions AUTO_INCREMENT = 46;
ALTER TABLE options AUTO_INCREMENT = 46;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `STUDENT_RANK`(IN `SID` INT)
BEGIN 
WITH RankedScores AS (
    SELECT
        NAME,
        SCORE.USN,
        TIME_TAKEN,
        SCORE,
        ROW_NUMBER() OVER (PARTITION BY NAME ORDER BY SCORE DESC, TIME_TAKEN ASC) AS RowNum
    FROM SCORE
    JOIN USERS ON SCORE.USN = USERS.USN
    WHERE SID = 1
)
SELECT NAME, USN, TIME_TAKEN, SCORE
FROM RankedScores
WHERE RowNum = 1
ORDER BY SCORE DESC, TIME_TAKEN ASC
END$$
DELIMITER ;

SET @p0='2'; SET @p1='1AY21CS153'; 
CALL `ATTEMPTS`(@p0, @p1);